version: '3.8'
services:
  chia-nodes:
    image: ghcr.io/chia-network/chia:latest
    ports:
      - "8444:8444"
      - "8555:8555"
      - "8562:8562"
      - "8575:8575"
      - "9256:9256"
    environment:
      CHIA_ROOT: /chia-data
      service: node
      self_hostname: 0.0.0.0
      keys: "persistent"
    volumes:
      - ~/.dig/chia-data:/chia-data
      - ~/.dig/chia_keys:/root/.chia_keys

  propagation-server:
    image: michaeltaylor3d/dig-propagation-server:latest
   # depends_on:
   #   - chia-nodes
    ports:
      - "4159:4159"
    volumes:
      - ~/.dig/remote:/.dig
    environment:
      - DIG_USERNAME=CHANGEME
      - DIG_PASSWORD=CHANGEME
      - DIG_FOLDER_PATH=/.dig
      - PORT=4159
      - REMOTE_NODE=1

  content-server:
    image: michaeltaylor3d/dig-content-server:latest
   # depends_on:
   #   - chia-nodes
    ports:
      - "80:80"
    volumes:
      - ~/.dig/remote:/.dig
    environment:
      - DIG_FOLDER_PATH=/.dig
      - PORT=80
      - REMOTE_NODE=1

networks:
  default:
    name: dig_network
