version: '3.8'
services:
  chia-nodes:
    image: ghcr.io/chia-network/chia:latest
    ports:
      - "8444:8444"
      - "8555:8555"
      - "8562:8562"
      - "8575:8575"
      - "9256:9256"
    environment:
      CHIA_ROOT: /chia-data
      service: node
      self_hostname: 0.0.0.0
      keys: "persistent"
    volumes:
      - ~/.dig/chia-data:/chia-data
      - ~/.dig/chia_keys:/root/.chia_keys

  propagation-server:
    image: michaeltaylor3d/dig-propagation-server:latest
    depends_on:
      - chia-nodes
    ports:
      - "4159:4159"
    volumes:
      - ~/.dig/stores:/.dig
    environment:
      - DIG_USERNAME=1
      - DIG_PASSWORD=1
      - DIG_FOLDER_PATH=/.dig
      - PORT=4159
      - DIG_MNEMONIC=tomato unaware wrist say genius boring exile fossil assault cruise horse twenty enroll fiction damage float time actor matrix security grocery search breeze damp

  content-server:
    image: michaeltaylor3d/dig-content-server:latest
    depends_on:
      - chia-nodes
    ports:
      - "80:80"
    volumes:
      - ~/.dig/stores:/.dig
    environment:
      - DIG_FOLDER_PATH=/.dig
      - PORT=80

networks:
  default:
    name: dig_network
